obs-ffmpeg: Add compile option for runtime amf loading
Add compile time option ENABLE_LOADING_AMF to allow or disallow
loading amf at runtime.

Currently the WIN32 system call to LoadLibraryExW returns in an
exception being thrown when a system does not have amf installed.

Exception thrown at 0x00007FFB6E1F53AC in obs64.exe: Microsoft C++
exception: char at memory location 0x0000000E806FD6A8.

This change provides a compile time flag which is checked at
runtime.  If ENABLE_LOADING_AMF is off, calls to amf_load() and
amf_unload() are not imported, nor are they called.